Employee/urls.py
from django.urls import path
from .views import (
    EmployeeAddView,
    EmployeeListView,
    EmployeeUpdateView,
    EmployeeDetailView,
)

app_name = 'Employee'

urlpatterns = [
    path('create',EmployeeAddView.as_view(),name='create-employee'),
    path('emplist',EmployeeListView.as_view(),name='employee-list'),
    path('<int:id>/update/', EmployeeUpdateView.as_view(), name='employee-update'),
    path('<int:id>/', EmployeeDetailView.as_view(), name='employee-detail'),
]

Swasthya/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
	path('', include('accounts.urls')),
    path('console/', include('console.urls')),
    path('employee/', include('Employee.urls')),
    path('leave/', include('leave.urls')),
    path('eattendance/', include('eattendance.urls')),
    path('med/', include('med.urls')),
    path('admin/', admin.site.urls),
]

leave/urls.py
from django.urls import path
from . import views
from .views import (
    LeaveRequestCreateView,
    LeaveDetailView,
    LeaveRequestListView,
    MonthwiseView,
)

app_name = 'leave'

urlpatterns = [
    path('<int:id>/create',LeaveRequestCreateView.as_view(),name='create-leave'),
    path('leaverequests',LeaveRequestListView.as_view(),name='leave-request-list'),
    #path('<int:id>/update/', EmployeeUpdateView.as_view(), name='employee-update'),
    path('<int:id>/', LeaveDetailView.as_view(), name='leave-detail'),
    path('<int:id>/approval',views.approve_leave_request,name='leave-approve'),
    path('<int:id>/reject',views.reject_leave,name='leave-reject'),
    path('leavemonthly',MonthwiseView.as_view(), name='leave-monthly'),
]

med/urls.py
from django.urls import path
from . import views

app_name = 'med'

urlpatterns = [
    path('visit/create',views.VisitCreateView.as_view(),name='create-visit'),
    path('visit/<int:id>/', views.VisitDetailView.as_view(), name='visit-detail'),

    path('diet/create',views.DietOrderView.as_view(),name='create-diet'),
    path('<int:id>/edit',views.DietOrderUpdateView.as_view(),name='leave-update'),
    path('diet/<int:id>/',views.DietOrderDetailView.as_view(),name='dietorder-detail'),
    path('diet/list/', views.DietOrderList.as_view(), name='list-diet'),

    path('ajax/load_rooms', views.load_rooms, name='ajax_load_rooms'), 
    path('ajax/load_beds', views.load_beds, name='ajax_load_beds'), 
    path('ajax/load_livesearch_ipno', views.livesearch_ipno, name='ajax_livesearch'), 
]

leave/models.py
from datetime import date, timezone
from django.db import models
from django.utils.translation import ugettext as _
from accounts.models import User
from django.utils import timezone
from datetime import datetime
from django.utils import timezone
from Employee.models import Employee
from .manager import ApprovedLeavesManager,LeaveTypeManager,LeavesAllottedTotalManager,LeavesRequestManager


# Model script


class LeaveType(models.Model):
    YES='YES'
    NO='NO'
    CANAPPLY = (
        (YES,YES),
        (NO,NO),
    )
    name = models.CharField(max_length=40)
    year = models.CharField(max_length=9)
    maximum_leaves = models.IntegerField()
    can_apply = models.CharField(max_length=3, choices=CANAPPLY)
    code=models.CharField(max_length=9)
    objects = LeaveTypeManager()
    def __str__(self):
        return self.name

class LeavesAllottedTotal(models.Model):
    leave_type = models.ForeignKey(LeaveType, on_delete=models.CASCADE)
    employee = models.ForeignKey(Employee, on_delete=models.CASCADE)
    year = models.CharField(max_length=9)
    total_leaves = models.IntegerField()
    objects = LeavesAllottedTotalManager()

    def __str__(self):
        return self.leave_type.name


class LeaveRequest(models.Model):
    APPROVED = 'Approved'
    PENDING = 'Pending'
    REJECTED = 'Rejected'
    CANCELLED = 'Cancelled'
    YES='YES'
    NO='NO'
    NA = 'NA'
    LEAVE_STATUS = (
        (APPROVED,APPROVED),
        (PENDING,PENDING),
        (REJECTED,REJECTED)
    )
    YESNO = (
        (YES,YES),
        (NO,NO)
    )
    employee = models.ForeignKey(Employee, on_delete=models.CASCADE)
    leavefrom = models.DateField()
    leavetill = models.DateField()
    purpose = models.CharField(max_length=100,null=True,blank=True)
    applied_date = models.DateField(default=timezone.now)
    comments = models.TextField(null=True, blank=True)
    is_sick = models.CharField(max_length=3,choices=YESNO)
    first_approver_status = models.CharField(max_length=12, choices=LEAVE_STATUS,null=True, blank=True)
    second_approver_status = models.CharField(max_length=12, choices=LEAVE_STATUS,null=True, blank=True)
    third_approver_status = models.CharField(max_length=12, choices=LEAVE_STATUS,null=True, blank=True)
    first_approver_remark = models.TextField(null=True, blank=True)
    second_approver_remark = models.TextField(null=True, blank=True)
    third_approver_remark = models.TextField(null=True, blank=True)
    #Overal state of a leave request independent of approvers
    leave_state = models.CharField(max_length=12, default=PENDING)
    created_by = models.ForeignKey(User, on_delete=models.CASCADE)
    objects = LeavesRequestManager()

    def __str__(self):
        return self.leave_state

    @property
    def get_next_approver(self):
        if(first_approver_status==PENDING):
            return '1'
        elif(second_approver_status==PENDING):
            return '2'
        elif(third_approver_status==PENDING):
            return '3'
        else:
            return '0'

    @property
    def is_leave_today(self):
        today = date.today()
        if (today >= self.leavefrom and today <= self.leavetill):
            return True
        return False

    @property
    def get_leave_duration(self):
        leave_days = self.leavetill-self.leavefrom
        return leave_days.days+1

class ApprovedLeaves(models.Model):
    employee = models.ForeignKey(Employee, on_delete=models.CASCADE)
    leavetype = models.ForeignKey(LeaveType, on_delete=models.CASCADE)
    leaves_taken = models.DecimalField(max_digits=3,decimal_places=1)
    leaverequest = models.ForeignKey(LeaveRequest, on_delete=models.CASCADE)
    objects = ApprovedLeavesManager()

class LeaveAudit(models.Model):
    action = models.CharField(max_length=200)
    user = models.ForeignKey(User, on_delete=models.DO_NOTHING)
    created = models.DateTimeField(default=timezone.now)

leave/views.py
import datetime
from django.shortcuts import render, get_object_or_404, HttpResponse, HttpResponseRedirect
from django.urls import reverse
from .forms import LeaveRequestForm
from .models import LeaveRequest, LeaveType, LeavesAllottedTotal, ApprovedLeaves
from Employee.models import Employee,LeaveApprover
from django.views.decorators.csrf import csrf_exempt
from django.db.models import Q
from django.contrib.auth.decorators import login_required
from django.views import View
from calendar import monthrange

# import generic FormView
from django.views.generic import (
    FormView,
    CreateView,
    UpdateView,
    ListView,
    DetailView,
)

class LeaveRequestCreateView(CreateView):
    ONE = 1
    TWO =2
    THREE =3
    FIVE = 5
    # specify the Form you want to use
    form_class = LeaveRequestForm
    # sepcify name of template
    template_name = "leave/leave_create.html"
    def get_success_url(self):
        return reverse('leave:leave-detail',args=(self.object.id,))

    def get_context_data(self,**kwargs):
        context = super(LeaveRequestCreateView,self).get_context_data(**kwargs)
        user = self.request.user
        employee = Employee.objects.get(user=user)
        context['employee']=employee
        return context

    def form_valid(self, form):
        # This method is called when valid form data has been POSTed.
        # It should return an HttpResponse.
        login_user = self.request.user
        employee = self.get_employee()
        form.instance.employee = employee
        form.instance.created_by = login_user
        emp_dept = employee.department
        approvers = LeaveApprover.objects.filter(department=emp_dept)
        loginuser_approve_pos = 0
        approver1 = None
        approver2 =None
        approver3 = None 
        #GOT ALL APPROVERS, NEED TO USE THIS VALUE
        approvers_dict = {}
        for a in approvers:
            approvers_dict[a.position]=a
            if a.position==self.ONE:
                approver1=a.approver
            if a.position==self.TWO:
                approver2=a.approver
            if a.position==self.THREE:
                approver3=a.approver
            if login_user==a.approver.user:
                loginuser_approve_pos = a.position # Login user is a leave approver and position of approval is a.position

        #print(a)
        leaves_exists_in = self.leave_entry_exists(form)
        if leaves_exists_in:
            form.add_error(None,"Leaves applied are overlapping with previously applied leave entries. Kindly check !")
            return super().form_invalid(form)

        leave_days_td = form.instance.leavetill-form.instance.leavefrom
        leave_days = leave_days_td.days+1
        print(leave_days)
        #return
        if leave_days == self.ONE: # Only 1 line manager approval is neede for 1 day leave
            form.instance.second_approver_status = LeaveRequest.NA 
            form.instance.third_approver_status = LeaveRequest.NA 
        elif leave_days < self.FIVE: # Only 2 line manager approval is neede for 1 day leave
            form.instance.third_approver_status = LeaveRequest.NA #
        #Leave request created by ownself and is a first level approver
        if employee.user == login_user:
            if employee == approver1:
                form.instance.first_approver_status = LeaveRequest.NA
                form.instance.second_approver_status = LeaveRequest.PENDING
                form.instance.first_approver_remark = form.instance.comments
            elif employee == approver2:
                form.instance.first_approver_status = LeaveRequest.NA
                form.instance.second_approver_status = LeaveRequest.NA
                form.instance.third_approver_status = LeaveRequest.PENDING
                form.instance.second_approver_remark = form.instance.comments 
            elif employee == approver3:
                form.instance.first_approver_status = LeaveRequest.NA
                form.instance.second_approver_status = LeaveRequest.NA
                form.instance.third_approver_status = LeaveRequest.APPROVED
                form.instance.third_approver_remark = form.instance.comments 
                form.instance.leave_state=LeaveRequest.APPROVED
            else:
                if leave_days==self.ONE:
                    form.instance.first_approver_status = LeaveRequest.PENDING
                    form.instance.first_approver_remark = form.instance.comments
                elif leave_days < self.FIVE:
                    form.instance.first_approver_status = LeaveRequest.PENDING
                    form.instance.second_approver_status = LeaveRequest.PENDING
                else:
                    form.instance.first_approver_status = LeaveRequest.PENDING
                    form.instance.second_approver_status = LeaveRequest.PENDING
                    form.instance.third_approver_status = LeaveRequest.PENDING
        #If Line manager is applying leave for his/her staff
        elif login_user==approver1.user:
            form.instance.first_approver_status = LeaveRequest.APPROVED
            form.instance.first_approver_remark = form.instance.comments
            if leave_days == self.ONE:
                form.instance.leave_state=LeaveRequest.APPROVED
        elif login_user==approver2.user:
            form.instance.first_approver_status = LeaveRequest.NA
            form.instance.second_approver_status = LeaveRequest.APPROVED
            form.instance.second_approver_remark = form.instance.comments 
            if leave_days < self.FIVE:
                form.instance.leave_state=LeaveRequest.APPROVED   
        elif login_user==approver3.user:
            form.instance.second_approver_status = LeaveRequest.NA
            form.instance.third_approver_status = LeaveRequest.APPROVED
            form.instance.third_approver_remark = form.instance.comments  
            form.instance.leave_state =  LeaveRequest.APPROVED
        else:
            form.add_error(None,"You are not an authorised person to apply leave. Please contact your Line Manager !")
            return super().form_invalid(form)
        # perform a action here
        print(form.cleaned_data)
        is_leave_approved = False
        if form.instance.leave_state == LeaveRequest.APPROVED:
            is_leave_approved = True
        self.object = form.save(commit=False)
        #Save all
        is_sick = form.cleaned_data['is_sick']
        form = self.object.save()
        #ret = distribute_leaves(form, leave_days, is_sick)

        cl_leaves_consumed = None
        el_leaves_consumed = None
        if is_sick == 'YES':
            make_sickleave()
        else:
            if is_leave_approved:
                self.manage_leaves(employee,leave_days,self.object)
                cl_type = LeaveType.objects.getLeaveTypeOnCode('CL')
                el_type = LeaveType.objects.getLeaveTypeOnCode('EL')
                cl_leaves_consumed = ApprovedLeaves.objects.getTotalSpecificLeave(cl_type,employee)
                el_leaves_consumed = ApprovedLeaves.objects.getTotalSpecificLeave(el_type,employee)
            
        #return HttpResponseRedirect(self.get_success_url())

        context = {'id':self.object.pk ,'CL': cl_leaves_consumed, 'EL': el_leaves_consumed,}
        print(context)
        return HttpResponseRedirect(reverse('leave:leave-detail',
                                        args=(self.object.pk,)))
        #return render(self.request, 'leave/leave_detail.html', context=context)

    def manage_leaves(self,employee,leave_demanded,form):
        leave_left = leave_demanded
        today = datetime.date.today()
        this_month = today.month
        cl_apply = 0
        el_apply =0
        lop_apply = 0
        cl_type = LeaveType.objects.getLeaveTypeOnCode('CL')
        el_type = LeaveType.objects.getLeaveTypeOnCode('EL')
        lop_type = LeaveType.objects.getLeaveTypeOnCode('LOP')
        #
        cl_yearly_allotted = LeavesAllottedTotal.objects.total(employee,cl_type)#.filter(leave_type=cl_type).first()
        cl_leaves_consumed = ApprovedLeaves.objects.getTotalSpecificLeave(cl_type,employee)
        el_yearly_allotted = LeavesAllottedTotal.objects.total(employee,el_type)
        el_leaves_consumed = ApprovedLeaves.objects.getTotalSpecificLeave(el_type,employee)
        #
        cl_inhand = cl_yearly_allotted.total_leaves - cl_leaves_consumed
        el_inhand = el_yearly_allotted.total_leaves - el_leaves_consumed
        #
        cl_can = this_month-cl_leaves_consumed

        if cl_can > 0:
            if cl_can <= leave_left:
                cl_apply = cl_can
                leave_left = leave_left - cl_can
            else:
                cl_apply = leave_left
                leave_left = 0

        if el_inhand > 0: # EL leaves are available
            if el_inhand >= leave_left:
                el_apply = leave_left
                leave_left = 0
            else:
                el_apply = el_inhand
                leave_left = leave_left - el_inhand
                if cl_inhand <= leave_left:
                    cl_apply = cl_apply + cl_inhand
                    leave_left = leave_left - cl_inhand
                else:
                    cl_apply = cl_apply + leave_left
                    leave_left = 0

        if leave_left > 0:
            lop_apply = leave_left 
            
        
        print('CL:' + str(cl_apply))
        print('EL:' + str(el_apply))
        print('LOP:' + str(leave_left))
        if cl_apply > 0:
            ApprovedLeaves.objects.create_me(employee,cl_type,cl_apply,form)
        if el_apply > 0:
            ApprovedLeaves.objects.create_me(employee,el_type,el_apply,form)
        if lop_apply > 0:
            ApprovedLeaves.objects.create_me(employee,lop_type,lop_apply,form)
        return

    def make_sickleave():
        pass

    def get_employee(self):
        id_ = self.kwargs.get("id")
        return get_object_or_404(Employee, id=id_)
    

leave/templates/leave/leave_create.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block structure %}
{% include 'inc/structure.html'%}
{% endblock %}
{% block content %}
{% load custom_tags %}
<form method="post" name="leaverequestform" id="id_leaverequestform" autocomplete="off">
    {% csrf_token %}
    {% if form.non_field_errors %}
    <div class="alert alert-danger" role="alert">
        {{ form.non_field_errors }}
    </div>
    {% endif %}
    <p>
    {{ form.source.errors }}
    {{ form.source }}
    </p>
        <!-- 2 column grid layout with text inputs for the first and last names -->
        <div class="row mb-4">
            <div class="col">
                <h5 class="card-title text-center">Leave Application</h5>
            </div>
        </div>
        <div class="row mb-4">
          <div class="col">
            <div class="form-outline">
                <span class="two-inputs">
                {{ form.leavefrom.errors }}
                {{ form.leavefrom|add_classes:'form-control' }}
                </span>
              <label class="form-label" for="leavefrom">From Date</label>
            </div>
          </div>
          <div class="col">
            <div class="form-outline">
                <span class="two-inputs">
                {{ form.leavetill.errors }}
                {{ form.leavetill|add_classes:'form-control' }}
                </span>
              <label class="form-label" for="leavetill">Till Date</label>
            </div>
          </div>
        </div>
        <div class="row mb-4">
            <div class="col">
                <div class="form-outline mb-4">
                    {{ form.purpose.errors }}
                    {{ form.purpose|add_classes:'form-control' }}
                <label class="form-label" for="purpose">Purpose</label>
                </div>
            </div>
            <div class="col">
                <div class="form-outline mb-4">
                    {{ form.is_sick.errors }}
                    {{ form.is_sick|add_classes:'form-control' }}
                <label class="form-label" for="purpose">Is this Sick Leave? </label>
                </div>
            </div>
        </div>
        <!-- Text input -->
        
        <!-- Message input -->
        <div class="row mb-4">
            <div class="col">
                <div class="form-outline mb-4">
                    {{ form.comments.errors }}
                    {{ form.comments|add_classes:'form-control' }}
                <label class="form-label" for="form6Example7">Comments</label>
                </div>
            </div>
        </div>
        <!-- Submit button -->
        <button type="submit" class="btn btn-primary btn-block mb-4">Apply Leave</button>
    </form>

{% endblock %}
{% block jscripts %}
<script>
    function on_submit_form(){
    }
    $('#id_leavefrom').keydown(function(e) {
        e.preventDefault();
        return false;
    });
    $('#id_leavetill').keydown(function(e) {
        e.preventDefault();
        return false;
    });

</script>
<script>
    $(function()
    {
    
        if (!window['console'])
        {
            window.console = {};
            window.console.log = function(){};
        }
        $.dateRangePickerLanguages['custom'] =
        {
        'selected': 'Choosed:',
        'days': 'Days',
        'apply': 'Close',
        'week-1' : 'Mon',
        'week-2' : 'Tue',
        'week-3' : 'Wed',
        'week-4' : 'Thu',
        'week-5' : 'Fri',
        'week-6' : 'Sat',
        'week-7' : 'Sun',
        'month-name': ['January','February','March','April','May','June','July','August','September','October','November','December'],
        'shortcuts' : 'Shortcuts',
        'past': 'Past',
        '7days' : '7days',
        '14days' : '14days',
        '30days' : '30days',
        'previous' : 'Previous',
        'prev-week' : 'Week',
        'prev-month' : 'Month',
        'prev-quarter' : 'Quarter',
        'prev-year' : 'Year',
        'less-than' : 'Date range should longer than %d days',
        'more-than' : 'Date range should less than %d days',
        'default-more' : 'Please select a date range longer than %d days',
        'default-less' : 'Please select a date range less than %d days',
        'default-range' : 'Please select a date range between %d and %d days',
        'default-default': 'This is costom language'
        };
        $('.two-inputs').dateRangePicker(
        {
            separator : ' to ',
            getValue: function()
            {
                if ($('#id_leavefrom').val() && $('#id_leavetill').val() )
                    return $('#id_leavefrom').val() + ' to ' + $('#id_leavetill').val();
                else
                    return '';
            },
            setValue: function(s,s1,s2)
            {
                $('#id_leavefrom').val(s1);
                $('#id_leavetill').val(s2);
            }
        });
    });
    </script>
<script>

    $(function () {
        $("#id_leavefrom1").datepicker({
            dateFormat: 'yy-mm-dd',
            numberOfMonths: 2,
            autoclose: true,
            changeMonth: true,
            changeYear: true,
            onSelect: function (selected) {
                var dt = new Date(selected);
                dt.setDate(dt.getDate());
                $("#id_leavetill").datepicker("option", "minDate", dt);
            }
        });
        $("#id_leavetill1").datepicker({
            dateFormat: 'yy-mm-dd',
            numberOfMonths: 2,
            autoclose: true,
            changeMonth: true,
            changeYear: true,
            onSelect: function (selected) {
                var dt = new Date(selected);
                dt.setDate(dt.getDate() );
                $("#id_leavefrom").datepicker("option", "maxDate", dt);
            }
        });
    }); 
    $("#id_leavetill").on('blur', function(){    
        //check_noleave_overlap();
    });
    $("#id_leavefrom").on('blur', function(){    
        //$("#id_leavetill").val() = '';
    });
    $(".btapply").click(function(e){
        alert('');
        //e.preventDefault();
        if (check_noleave_overlap()){
            //event.preventDefault();
            return false;
        }
        $('#id_leaverequestform').submit();
        //return (true);
    });
    
    function form_validate(){
        document.leaverequestform.submit();
        // retval = check_leave_overlap();
        // alert(retval );
        //if(retval) document.leaverequestform.submit();
        //return(retval);
    }

</script>
{% endblock %}

{% block footer%}
{% include 'inc/footer.html' %}
{% endblock %}

leave/templates/leave/leave_detail.html
{% extends 'base.html' %}
{% block structure %}
{% include 'inc/structure.html'%}
{% endblock %}
{% block content %}
{% load custom_tags %}
<div class="row">
    <div class="col-sm" style="background-color:rgb(255, 255, 255);"><h3>Casual Leave <span class="badge bg-primary">{{ leavebalance|dictitem:'CL' }}</span></h3></div>
    <div class="col-sm" style="background-color:rgb(217, 218, 221);"><h3>Earned Leave <span class="badge bg-success">{{ leavebalance|dictitem:'EL' }}</span></h3></div>
    <div class="col-sm" style="background-color:rgb(255, 255, 255);"><h3>Sick Leave <span class="badge bg-info">{{ leavebalance|dictitem:'SL' }}</span></h3></div>
    <div class="col-sm" style="background-color:rgb(217, 218, 221);"><h3>Loss of Pay <span class="badge bg-danger">{{ leavebalance|dictitem:'LOP' }}</span></h3></div>

</div>
<br/><br/>
<div class="row">
    <div class="col-sm-3" style="background-color:rgb(201, 201, 187);">Leave from</div>
    <div class="col-sm-9" style="background-color:rgb(238, 238, 238);">{{ object.leavefrom }}</div>
</div>
<div class="row">
    <div class="col-sm-3" style="background-color:rgb(246, 250, 246);">Leave Till</div>
    <div class="col-sm-9" style="background-color:rgb(250, 250, 250);">{{ object.leavetill }}</div>
</div>
<div class="row">
    <div class="col-sm-3" style="background-color:rgb(201, 201, 187);">Leave Status</div>
    <div class="col-sm-9" style="background-color:rgb(238, 238, 238);">{{ object.leave_state }}</div>
</div>
<div class="row">
    <div class="col-sm-3" style="background-color:rgb(255, 255, 255);">Purpose</div>
    <div class="col-sm-9" style="background-color:rgb(252, 253, 251);">{{ object.purpose }}</div>
</div>
  <br>
{% endblock %}
{% block footer%}
{% include 'inc/footer.html' %}
{% endblock %}

leave/templates/leave/leave_monthly.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block structure %}
{% include 'inc/structure.html'%}
{% endblock %}
{% block content %}
<div class="">
    <div class="d-flex text-white text-uppercase">
      <div class="p-2 flex-shrink-1 bg-warning"></div>
      <div class="p-2 w-100 bg-dark"><b>{{monthname}}</b></div>
      <div class="p-2 flex-shrink-1 bg-warning"></div>
    </div>
    
    {{ table|safe }}
    <!-- <table border="1" width="100%" style="border-color: rgb(199, 190, 199);">
      <thead style="background-color:rgb(236, 236, 235)">
        <tr align="center">
          <th class="p-2">Name</th>
          {% for d in days%}
          <th>{{ d }}</th>
          {% endfor %}
        </tr>
      </thead>
      <tbody>
        {% for emp in employees %}
        <tr>   
          <td class="p-2">{{emp.get_full_name}}</td>
          {% for d in days%}
          {% if d > 4%}
          <td width=3% class=""><i style="color: green;" class="ti-control-record icon-green "></i></td>
          {% else%}
          <td width=3% class="table-danger"><i style="color: green;" class="ti-control-record icon-green "></i></td>
          {% endif %}
          {% endfor %}
        </tr>
        {% endfor %}
      </tbody>
    </table> -->
    
    
</div>
{% endblock %}
{% block footer%}
<script>
    <!--
            function getConfirmation() {
               var retVal = confirm("Do you want to continue ?");
               if( retVal == true ) {
                  return true;
               } else {
                  return false
               }
            }
         //-->
 </script>
{% include 'inc/footer.html' %}
{% endblock %}

leave/templates/leave/leave_request_list.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block structure %}
{% include 'inc/structure.html'%}
{% endblock %}
{% block content %}
<div class="table-responsive-sm">
    <div class="d-flex text-white text-uppercase">
      <div class="p-2 flex-shrink-1 bg-warning"></div>
      <div class="p-2 w-100 bg-secondary"><h4><b>Leave Requests</b></h4></div>
      <div class="p-2 flex-shrink-1 bg-warning"></div>
    </div>
    <table class="table table-sm table-bordered table-striped mb-0">
      <thead>
        <tr>
          <th scope="col">Employee</th>
          <th scope="col">Leave Date</th>
          <th scope="col">Total Days</th>
          <th scope="col">Status</th>
          <th scope="col"></th>
        </tr>
      </thead>
      <tbody>
{% for instance in requests %}
        <tr> 
          <td><a href="{% url 'Employee:employee-detail' id=instance.id %}">{{ instance.employee.emp_code|add:" - "|add:instance.employee.get_full_name }}</a></td>
          <td><a href="{% url 'leave:leave-detail' id=instance.id  %}" title="Click to View" class="btn btn-sm btn-primary btn-outline-primary" 
            role="button" aria-pressed="true"><b>{{ instance.leavefrom }} -- {{ instance.leavetill }}</b></a></td>
          <td>{{ instance.get_leave_duration }} Day/s</td>
          {% if instance.first_approver_status == instance.PENDING and instance.leave_state == instance.PENDING %}
          <td>Level-1 Pending</td>
          {% elif instance.second_approver_status == instance.PENDING and instance.leave_state == instance.PENDING %}
          <td>Level-2 Pending</td>
          {% else %}
          <td></td>
          {% endif%}
          <td><a href="{% url 'leave:leave-approve' id=instance.id  %}" class="btn btn-success btn-sm active" 
            role="button" aria-pressed="true" onclick = "return getConfirmation();">Approve</a>
            <a href="{% url 'leave:leave-reject' id=instance.id  %}" class="btn btn-danger btn-sm active" role="button" aria-pressed="true">Reject</a>
          </td>
        </tr>
{% endfor %}
      </tbody>
    </table>
</div>
{% endblock %}
{% block footer%}
<script>
    <!--
            function getConfirmation() {
               var retVal = confirm("Do you want to continue ?");
               if( retVal == true ) {
                  return true;
               } else {
                  return false
               }
            }
         //-->
 </script>
{% include 'inc/footer.html' %}
{% endblock %}