Swasthya/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
	path('', include('accounts.urls')),
    path('console/', include('console.urls')),
    path('employee/', include('Employee.urls')),
    path('leave/', include('leave.urls')),
    path('eattendance/', include('eattendance.urls')),
    path('med/', include('med.urls')),
    path('admin/', admin.site.urls),
]

eattendance/urls.py
from django.urls import path
from .views.shift_views import (
    ShiftCreateView,
    ShiftDetailView,
    ShiftUpdateView,
    ShiftListView,
)
from .views.roster_view import(
    RosterCreateView,
)
app_name = 'eattendance'
urlpatterns = [
    # shift urls
    path('shift/create/', ShiftCreateView.as_view(), name='shift-create'),
    path('shift/<int:pk>/', ShiftDetailView.as_view(), name='shift-detail'),
    path('shift/<int:pk>/update', ShiftUpdateView.as_view(),name='shift-update'),
    path('shifts/', ShiftListView.as_view(), name='shifts'),
    # roster urls
    path('roster/create/', RosterCreateView.as_view(), name='roster-create'),
]

med/urls.py
from django.urls import path
from . import views

app_name = 'med'

urlpatterns = [
    path('visit/create',views.VisitCreateView.as_view(),name='create-visit'),
    path('visit/<int:id>/', views.VisitDetailView.as_view(), name='visit-detail'),

    path('diet/create',views.DietOrderView.as_view(),name='create-diet'),
    path('<int:id>/edit',views.DietOrderUpdateView.as_view(),name='leave-update'),
    path('diet/<int:id>/',views.DietOrderDetailView.as_view(),name='dietorder-detail'),
    path('diet/list/', views.DietOrderList.as_view(), name='list-diet'),

    path('ajax/load_rooms', views.load_rooms, name='ajax_load_rooms'), 
    path('ajax/load_beds', views.load_beds, name='ajax_load_beds'), 
    path('ajax/load_livesearch_ipno', views.livesearch_ipno, name='ajax_livesearch'), 
]

eattendance/models.py
from models.backengine import *
from models.attendance import *
from django.db import models

eattendance/models/attendance.py
import datetime
from django.db.models.fields import related
from django.utils import timezone
from django.urls import reverse
from django.db import models
from Employee.models import Employee
from accounts.models import User


class Holidays(models.Model):
    name = models.CharField(max_length=30)
    holiday = models.DateField()
    desciption = models.CharField(max_length=200,null=True,blank=True)
    created_by = models.ForeignKey(User, on_delete=models.DO_NOTHING)
    created_date = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.name

class Shift(models.Model):
    ENABLE_CHOICES = (
        (True, 'Enable'),
        (False, 'Disable')
    )   
    WEEKEND_CHOICES = (
        ('l','Location based'),
        ('s','Shift based'),
    )
    SHIFT_TYPES = (
        ('Flexible-day', 'Flexible(Day)'),
        ('Flexible-night', 'Flexible(Night)'),
        ('fixed-shift-time','Fixed Shift Time'),
    )
    name = models.CharField(max_length=20,null=True, blank=True)
    shift_from = models.TimeField(null=True, blank=True)
    shift_to = models.TimeField(null=True,blank=True)
    shift_margin = models.BooleanField(choices=ENABLE_CHOICES)  
    margin_before = models.TimeField(null=True,blank=True)
    margin_after = models.TimeField(null=True,blank=True)
    shift_type = models.CharField(max_length=35,choices=SHIFT_TYPES)
    created_by = models.ForeignKey(User, on_delete=models.DO_NOTHING,null=True,blank=True,related_name='createdusers')
    created_date = models.DateTimeField(default=timezone.now)
    updated_by = models.ForeignKey(User, on_delete=models.DO_NOTHING,null=True,blank=True,related_name='updatedusers')
    updated_date = models.DateTimeField(null=True,blank=True)

    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse('eattendance:shift-detail', args=[self.id])

class Roster(models.Model):
    YES_NO_CHOICES = (
        (True, 'Yes'),
        (False, 'No')
    )   
    employee = models.ForeignKey(Employee,on_delete=models.DO_NOTHING)
    roster_date = models.DateField(null=True)
    is_weekend = models.BooleanField(choices=YES_NO_CHOICES)
    shift = models.ForeignKey(Shift,on_delete=models.DO_NOTHING)
    created_by = models.ForeignKey(User, on_delete=models.DO_NOTHING,related_name='createdrosterusers')
    created_date = models.DateTimeField(default=timezone.now)
    updated_by = models.ForeignKey(User, on_delete=models.DO_NOTHING,null=True,blank=True,related_name='updatedrosterusers')
    updated_date = models.DateTimeField(default=timezone.now,null=True,blank=True)

class DailyAttendance(models.Model):
    in_time = models.DateTimeField(null=True)
    out_time = models.DateTimeField(null=True)
    employee = models.ForeignKey(Employee,on_delete=models.DO_NOTHING)
    created_by = models.ForeignKey(User, on_delete=models.DO_NOTHING,related_name='cbdausers')
    created_date = models.DateTimeField(default=timezone.now)
    updated_by = models.ForeignKey(User, on_delete=models.DO_NOTHING,null=True,blank=True,related_name='updatedadusers')
    updated_date = models.DateTimeField(default=timezone.now,null=True,blank=True)

eattendance/models/backengine.py
from django.db import models

class Devicelogs42021(models.Model):
    use_db = 'second'
    devicelogid = models.IntegerField(db_column='DeviceLogId',primary_key=True)  
    downloaddate = models.DateTimeField(db_column='DownloadDate', blank=True, null=True)  
    deviceid = models.IntegerField(db_column='DeviceId', blank=True, null=True)  
    userid = models.CharField(db_column='UserId', max_length=50, blank=True, null=True)  
    logdate = models.DateTimeField(db_column='LogDate', blank=True, null=True)  
    direction = models.CharField(db_column='Direction', max_length=100, blank=True, null=True)  
    attdirection = models.CharField(db_column='AttDirection', max_length=255, blank=True, null=True)  
    c1 = models.CharField(db_column='C1', max_length=255, blank=True, null=True)  
    c2 = models.CharField(db_column='C2', max_length=255, blank=True, null=True)  
    c3 = models.CharField(db_column='C3', max_length=255, blank=True, null=True)  
    c4 = models.CharField(db_column='C4', max_length=255, blank=True, null=True)  
    c5 = models.CharField(db_column='C5', max_length=255, blank=True, null=True)  
    c6 = models.CharField(db_column='C6', max_length=255, blank=True, null=True)  
    c7 = models.CharField(db_column='C7', max_length=255, blank=True, null=True)  
    workcode = models.CharField(db_column='WorkCode', max_length=100, blank=True, null=True)  
    updateflag = models.IntegerField(db_column='UpdateFlag', blank=True, null=True)  
    isapproved = models.IntegerField(db_column='IsApproved', blank=True, null=True)  
    employeeimage = models.TextField(db_column='EmployeeImage', blank=True, null=True)  
    filename = models.CharField(db_column='FileName', max_length=255, blank=True, null=True)  
    longitude = models.CharField(db_column='Longitude', max_length=255, blank=True, null=True)  
    latitude = models.CharField(db_column='Latitude', max_length=255, blank=True, null=True)  
    createddate = models.DateTimeField(db_column='CreatedDate', blank=True, null=True)  
    lastmodifieddate = models.DateTimeField(db_column='LastModifiedDate', blank=True, null=True)  
    locationaddress = models.CharField(db_column='LocationAddress', max_length=4000, blank=True, null=True)  
    bodytemperature = models.FloatField(db_column='BodyTemperature', blank=True, null=True)  
    is_maskon = models.IntegerField(db_column='IsMaskOn', blank=True, null=True)  

    def __str__(self):
        return self.userid + " : " + str(self.logdate)

    class Meta:
        managed = False
        db_table = 'DeviceLogs_4_2021'

class Ins(models.Model):
    ins = models.CharField(max_length=20)


class Devicelogs(models.Model):
    devicelogid = models.IntegerField(primary_key=True)  
    downloaddate = models.DateTimeField(blank=True, null=True)  
    deviceid = models.IntegerField(blank=True, null=True)  
    userid = models.CharField(max_length=50, blank=True, null=True)  
    logdate = models.DateTimeField(blank=True, null=True)  
    direction = models.CharField(max_length=100, blank=True, null=True)  
    attdirection = models.CharField(max_length=255, blank=True, null=True)  
    c1 = models.CharField(max_length=255, blank=True, null=True)  
    c2 = models.CharField(max_length=255, blank=True, null=True)  
    c3 = models.CharField(max_length=255, blank=True, null=True)  
    c4 = models.CharField(max_length=255, blank=True, null=True)  
    c5 = models.CharField(max_length=255, blank=True, null=True)  
    c6 = models.CharField(max_length=255, blank=True, null=True)  
    c7 = models.CharField(max_length=255, blank=True, null=True)  
    workcode = models.CharField(max_length=100, blank=True, null=True)  
    updateflag = models.IntegerField(blank=True, null=True)  
    isapproved = models.IntegerField(blank=True, null=True)  
    employeeimage = models.TextField(blank=True, null=True)  
    filename = models.CharField(max_length=255, blank=True, null=True)  
    longitude = models.CharField(max_length=255, blank=True, null=True)  
    latitude = models.CharField(max_length=255, blank=True, null=True)  
    createddate = models.DateTimeField(blank=True, null=True)  
    lastmodifieddate = models.DateTimeField(blank=True, null=True)  
    locationaddress = models.CharField(max_length=4000, blank=True, null=True)  
    bodytemperature = models.FloatField(blank=True, null=True)  
    is_maskon = models.IntegerField(blank=True, null=True)  

    def __str__(self):
        return self.userid + " : " + self.logdate

eattendance/forms.py
from django.forms import fields
from .models.attendance import Roster, Shift
from django import forms
from Employee.models import Employee

class ShiftCreateForm(forms.ModelForm):
    SHIFT_CHOICES = (
        ('fixed-shift-time','Fixed Shift Time'),
    )
    shift_type = forms.ChoiceField(choices=SHIFT_CHOICES,required=True)
    shift_from = forms.TimeField(widget=forms.TextInput(attrs={'min':'00:00','max': '23:59','type': 'time'}), required=False)
    shift_to = forms.TimeField(widget=forms.TextInput(attrs={'min':'00:00','max': '23:59','type': 'time'}), required=False)
    margin_before = forms.TimeField(widget=forms.TextInput(attrs={'min':'00:00','max': '23:59','type': 'time'}), required=False)
    margin_after = forms.TimeField(widget=forms.TextInput(attrs={'min':'00:00','max': '23:59','type': 'time'}), required=False)
   
    class Meta:
        model = Shift
        exclude = ('created_date',)
        fields = (
            'name', 'shift_from','shift_to','shift_margin','margin_before','margin_after',
            'shift_type','created_by',
        )
    
    def __init__(self, *args, **kwargs):
        self.created_by = kwargs.pop('user',[])
        super(ShiftCreateForm, self).__init__(*args, **kwargs)
        self.base_fields['shift_type'].initial = 'Fixed Shift Time'


class RosterCreateForm(forms.ModelForm):
    employee = forms.ModelChoiceField(None)
    duty_from = forms.DateField(required=True)
    duty_till = forms.DateField(required=True)
    
    class Meta:
        model = Roster
        exclude = ('created_date',)
        fields = ('employee','shift',)
    
    # def __init__(self, department, *args, **kwargs):
    #     super(RosterCreateForm, self).__init__(*args, **kwargs)
    #     self.fields['employee'].queryset = Employee.objects.filter(department__in=department)

eattendance/views/roster_view.py
from Employee.models import LeaveApprover,Employee
import datetime
from django.shortcuts import render,HttpResponseRedirect,get_object_or_404
from ..forms import RosterCreateForm
from ..models.attendance import Roster,Shift
from django.core.exceptions import ObjectDoesNotExist

from django.views.generic import (
    FormView,
    CreateView,
    UpdateView,
    ListView,
    DetailView,
)
class RosterCreateView(CreateView):
    template_name = 'eattendance/roster_create.html'
    form_class = RosterCreateForm
    model = Roster

    def get_initial (self):
        user = self.request.user
        try:
            user_emp = Employee.objects.get(user=user)
            apprs = LeaveApprover.objects.get_departments(user_emp)
            depts = []
            for a in apprs:
                depts.append(a.department)
                print(a)
            #print(depts)
            emps = Employee.objects.filter(department__in=depts)
            print(emps.query)
            return {'employee': emps}
        except ObjectDoesNotExist:
            return None

    def get_context_data(self,**kwargs):
        context = super(RosterCreateView,self).get_context_data(**kwargs)
        user = self.request.user
        employee = Employee.objects.get(user=user)
        context['employee']=employee
        return context

    def form_valid(self, form):
        print('Inside form_valid')
        self.object = form.save(commit=False)
        self.object.created_by=self.request.user
        #print(self.request.shift_from_)
        self.object.save()
        #print(self.get_success_url())
        return HttpResponseRedirect(self.get_success_url())

eattendance/views/shift_views.py
import datetime
from django.shortcuts import render,HttpResponseRedirect,get_object_or_404
from ..forms import ShiftCreateForm
from ..models import Shift
from Employee.models import Employee

from django.views.generic import (
    FormView,
    CreateView,
    UpdateView,
    ListView,
    DetailView,
)

class ShiftListView(ListView):
    model = Shift
    def get_context_data(self,**kwargs):
        context = super(ShiftListView,self).get_context_data(**kwargs)
        user = self.request.user
        employee = Employee.objects.get(user=user)
        context['employee']=employee
        return context

class ShiftCreateView(CreateView):
    template_name = 'eattendance/shift_create.html'
    form_class = ShiftCreateForm
    model = Shift

    def get_context_data(self,**kwargs):
        context = super(ShiftCreateForm,self).get_context_data(**kwargs)
        user = self.request.user
        employee = Employee.objects.get(user=user)
        context['employee']=employee
        return context

    def form_valid(self, form):
        print('Inside form_valid')
        self.object = form.save(commit=False)
        self.object.created_by=self.request.user
        #print(self.request.shift_from_)
        self.object.save()
        #print(self.get_success_url())
        return HttpResponseRedirect(self.get_success_url())

class ShiftUpdateView(UpdateView):
    model = Shift
    form_class = ShiftCreateForm
    template_name = 'eattendance/shift_create.html'

    def get_object(self, *args, **kwargs):
        shift = get_object_or_404(Shift, pk=self.kwargs['pk'])
        return shift

    def get_context_data(self,**kwargs):
        context = super(ShiftUpdateView,self).get_context_data(**kwargs)
        user = self.request.user
        employee = Employee.objects.get(user=user)
        context['employee']=employee
        return context

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.updated_by=self.request.user
        self.object.updated_date = datetime.date.today()
        #print(self.request.shift_from_)
        self.object.save()
        #print(self.get_success_url())
        return HttpResponseRedirect(self.get_success_url())

    # def get_success_url(self, *args, **kwargs):
    #     return reverse("some url name")

class ShiftDetailView(DetailView):
    model = Shift

    def get_context_data(self,**kwargs):
        context = super(ShiftDetailView,self).get_context_data(**kwargs)
        user = self.request.user
        employee = Employee.objects.get(user=user)
        context['employee']=employee
        return context

eattendance/templates/eattendance/roster_create.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block structure %}
{% include 'inc/structure.html'%}
{% endblock %}
{% block content %}
{% load eatt_tags %}
{% csrf_token %}
<form method="post" name="rostercreateform" id="rostercreateform" autocomplete="off">
    {% csrf_token %}
    {% if form.non_field_errors %}
    <div class="alert alert-danger" role="alert">
        {{ form.non_field_errors }}
    </div>
    {% endif %}
    <p>
    {{ form.source.errors }}
    {{ form.source }}
    </p>
    <!-- 2 column grid layout with text inputs for the first and last names -->
    <div class="card-details">
        <h3 class="title">Roster Details</h3>
        <div class="row">
            <div class="form-group col-sm-12">
              <label for="card-holder">Employee</label>
              {{ form.employee|add_classes:'form-control' }}
            </div>
        </div>
        <div class="row">
          <div class="form-group col-sm-6">
            <label for="card-holder">Duty starts from</label>
            {{ form.duty_from|add_classes:'form-control' }}
          </div>
          
          <div class="form-group col-sm-6">
            <label for="">Duty ends till</label>
            <div class="input-group expiration-date">
              {{ form.duty_till|add_classes:'form-control' }}
            </div>
            
          </div>
        </div>
        
        <div class="row">

          <div class="form-group col-sm-12">
            <button type="submit" class="btn btn-primary btn-block">Proceed</button>
          </div>
        </div>
    </div>
  </div>
</form>

{% endblock %}

{% block footer%}

{% include 'inc/footer.html' %}
<script>
    marginbefore= document.getElementById('id_margin_before');
    marginafter = document.getElementById('id_margin_after');
    $(function () {
        marginafter.disabled = true;
        marginbefore.disabled = true;
    });
    $('#id_shift_margin').change(function(e){
        if ( $('#id_shift_margin').val()=='True' ){
            marginafter.disabled = false;
            marginbefore.disabled = false;
        }else{
            marginafter.disabled = true;
            marginbefore.disabled = true;
        }
    }); 
</script>
{% endblock %}

eattendance/templates/eattendance/shift_create.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block structure %}
{% include 'inc/structure.html'%}
{% endblock %}
{% block content %}
{% load eatt_tags %}
{% csrf_token %}
<form method="post" name="shiftcreateform" id="shiftcreateform" autocomplete="off">
    {% csrf_token %}
    {% if form.non_field_errors %}
    <div class="alert alert-danger" role="alert">
        {{ form.non_field_errors }}
    </div>
    {% endif %}
    <p>
    {{ form.source.errors }}
    {{ form.source }}
    </p>
    <!-- 2 column grid layout with text inputs for the first and last names -->
    <div class="card-details">
        <h3 class="title">Shift Details</h3>
        <div class="row">
            <div class="form-group col-sm-12">
              <label for="card-holder">Shift Type</label>
              {{ form.shift_type|add_classes:'form-control' }}
            </div>
        </div>
        <div class="row">
          <div class="form-group col-sm-4">
            <label for="card-holder">Shift Title</label>
            {{ form.name|add_classes:'form-control' }}
          </div>
          
          <div class="form-group col-sm-2">
            <label for="">Shift from</label>
            <div class="input-group expiration-date">
                {{ form.shift_from|add_classes:'form-control' }}
            </div>
            
          </div>
          <div class="form-group col-sm-2">
            <label for="">Shift till</label>
            <div class="input-group expiration-date">
                {{ form.shift_to|add_classes:'form-control' }}
            </div>
          </div>
        </div>
        <div class="row">
            <div class="form-group col-sm-4">
                <label for="card-holder">Shift Margin</label>
                {{ form.shift_margin|add_classes:'form-control' }}
              </div>
            <div class="form-group col-sm-2">
                <label for="">Margin from</label>
                <div class="input-group expiration-date">
                    {{ form.margin_before|add_classes:'form-control' }}
                </div>
                
              </div>
              <div class="form-group col-sm-2">
                <label for="">Margin till</label>
                <div class="input-group expiration-date">
                    {{form.margin_after|add_classes:'form-control'}}
                </div>
              </div>
        </div>
        <div class="row">

          <div class="form-group col-sm-12">
            <button type="submit" class="btn btn-primary btn-block">Proceed</button>
          </div>
        </div>
    </div>
  </div>
</form>

{% endblock %}

{% block footer%}

{% include 'inc/footer.html' %}
<script>
    marginbefore= document.getElementById('id_margin_before');
    marginafter = document.getElementById('id_margin_after');
    $(function () {
        marginafter.disabled = true;
        marginbefore.disabled = true;
    });
    $('#id_shift_margin').change(function(e){
        if ( $('#id_shift_margin').val()=='True' ){
            marginafter.disabled = false;
            marginbefore.disabled = false;
        }else{
            marginafter.disabled = true;
            marginbefore.disabled = true;
        }
    }); 
</script>
{% endblock %}

eattendance/templates/eattendance/shift_detail.html
{% extends 'base.html' %}
{% block structure %}
{% include 'inc/structure.html'%}
{% endblock %}
{% block content %}

<h1>{{ object.name }}</h1>
<p>{{ object.shift_from }}</p>
<p>{{ object.shift_to}}</p>

{% endblock %}
{% block footer%}
{% include 'inc/footer.html' %}
{% endblock %}

eattendance/templates/eattendance/shift_list.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block structure %}
{% include 'inc/structure.html'%}
{% endblock %}
{% block content %}
<div class="table-responsive-sm">

    <table class="table table-sm table-bordered table-striped mb-0">
      <thead>
        <tr>
          <th scope="col">#</th>
          <th scope="col">Shift name</th>
          <th scope="col">Shift Type</th>
          <th scope="col">From</th>
          <th scope="col">Margin From</th>
          <th scope="col">Margin Till</th>
        </tr>
      </thead>
      <tbody>
{% for instance in object_list %}
        <tr>
          <th scope="row">{{ forloop.counter }}</th>
          <td><a href="{% url 'eattendance:shift-detail' pk=instance.id %}">{{ instance.name }}</a></td>
          <td>{{ instance.shift_type }}</td>
          <td>{{ instance.shift_from }}</td>
          <td>{{ instance.shift_to }}</td>
          <td>{{ instance.margin_before }}</td>
          <td>{{ instance.margin_after }}</td>
          <td><a href="{% url 'eattendance:shift-update' pk=instance.id  %}" class="btn btn-info btn-sm success" role="button" aria-pressed="true">Edit</a></td>
        </tr>
{% endfor %}
      </tbody>
    </table>
</div>
{% endblock %}
{% block footer%}
{% include 'inc/footer.html' %}
{% endblock %}