Swasthya/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
	path('', include('accounts.urls')),
    path('console/', include('console.urls')),
    path('employee/', include('Employee.urls')),
    path('leave/', include('leave.urls')),
    path('eattendance/', include('eattendance.urls')),
    path('med/', include('med.urls')),
    path('admin/', admin.site.urls),
]

med/urls.py
from django.urls import path
from . import views

app_name = 'med'

urlpatterns = [
    path('visit/create',views.VisitCreateView.as_view(),name='create-visit'),
    path('visit/<int:id>/', views.VisitDetailView.as_view(), name='visit-detail'),

    path('diet/create',views.DietOrderView.as_view(),name='create-diet'),
    path('<int:id>/edit',views.DietOrderUpdateView.as_view(),name='leave-update'),
    path('diet/<int:id>/',views.DietOrderDetailView.as_view(),name='dietorder-detail'),
    path('diet/list/', views.DietOrderList.as_view(), name='list-diet'),

    path('ajax/load_rooms', views.load_rooms, name='ajax_load_rooms'), 
    path('ajax/load_beds', views.load_beds, name='ajax_load_beds'), 
    path('ajax/load_livesearch_ipno', views.livesearch_ipno, name='ajax_livesearch'), 
]

diet/models.py
from django.db import models
from med.models import Visit

class DietItemCategory(models.Model):
    name = models.CharField(models.Model)
    def __str__(self):
        retun self.name

class DietType(models.Model):
    name = models.CharField(models.Model)
    def __str__(self):
        retun self.name

class DietItem(models.Model):                
    name = models.CharField(max_length=120)
    category = models.ForeignKey(DietItemCategory, on_delete=DO_NOTHING)
    dietype= models.ForeignKey(DietType, on_delete=DO_NOTHING)
    rate = models.DecimalField(max_digits=10, decimal_places=2)

class DietChart(models.Model):
    MORNING = 'Morning'
    LUNCH = 'Lunch'
    DINNER = 'Dinner'
    SPECIAL = 'Special'
    SLOT = (
        (MORNING,MORNING),
        (LUNCH,LUNCH),
        (DINNER,DINNER),
        (SPECIAL,SPECIAL),
    )
    patient = models.ForeignKey(Visit, on_delete=CASCADE)
    diet_item = models.ForeignKey(DietItem, on_delete=CASCADE)
    slot = models.ForeignKey(models.CharField(max_length=15,choices=SLOT))
    instructions = models.TextField(null=True, blank=True)
    time=models.TimeField(null=True, blank=True)

eattendance/models/attendance.py
import datetime
from django.db.models.fields import related
from django.utils import timezone
from django.urls import reverse
from django.db import models
from Employee.models import Employee
from accounts.models import User


class Holidays(models.Model):
    name = models.CharField(max_length=30)
    holiday = models.DateField()
    desciption = models.CharField(max_length=200,null=True,blank=True)
    created_by = models.ForeignKey(User, on_delete=models.DO_NOTHING)
    created_date = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.name

class Shift(models.Model):
    ENABLE_CHOICES = (
        (True, 'Enable'),
        (False, 'Disable')
    )   
    WEEKEND_CHOICES = (
        ('l','Location based'),
        ('s','Shift based'),
    )
    SHIFT_TYPES = (
        ('Flexible-day', 'Flexible(Day)'),
        ('Flexible-night', 'Flexible(Night)'),
        ('fixed-shift-time','Fixed Shift Time'),
    )
    name = models.CharField(max_length=20,null=True, blank=True)
    shift_from = models.TimeField(null=True, blank=True)
    shift_to = models.TimeField(null=True,blank=True)
    shift_margin = models.BooleanField(choices=ENABLE_CHOICES)  
    margin_before = models.TimeField(null=True,blank=True)
    margin_after = models.TimeField(null=True,blank=True)
    shift_type = models.CharField(max_length=35,choices=SHIFT_TYPES)
    created_by = models.ForeignKey(User, on_delete=models.DO_NOTHING,null=True,blank=True,related_name='createdusers')
    created_date = models.DateTimeField(default=timezone.now)
    updated_by = models.ForeignKey(User, on_delete=models.DO_NOTHING,null=True,blank=True,related_name='updatedusers')
    updated_date = models.DateTimeField(null=True,blank=True)

    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse('eattendance:shift-detail', args=[self.id])

class Roster(models.Model):
    YES_NO_CHOICES = (
        (True, 'Yes'),
        (False, 'No')
    )   
    employee = models.ForeignKey(Employee,on_delete=models.DO_NOTHING)
    roster_date = models.DateField(null=True)
    is_weekend = models.BooleanField(choices=YES_NO_CHOICES)
    shift = models.ForeignKey(Shift,on_delete=models.DO_NOTHING)
    created_by = models.ForeignKey(User, on_delete=models.DO_NOTHING,related_name='createdrosterusers')
    created_date = models.DateTimeField(default=timezone.now)
    updated_by = models.ForeignKey(User, on_delete=models.DO_NOTHING,null=True,blank=True,related_name='updatedrosterusers')
    updated_date = models.DateTimeField(default=timezone.now,null=True,blank=True)

class DailyAttendance(models.Model):
    in_time = models.DateTimeField(null=True)
    out_time = models.DateTimeField(null=True)
    employee = models.ForeignKey(Employee,on_delete=models.DO_NOTHING)
    created_by = models.ForeignKey(User, on_delete=models.DO_NOTHING,related_name='cbdausers')
    created_date = models.DateTimeField(default=timezone.now)
    updated_by = models.ForeignKey(User, on_delete=models.DO_NOTHING,null=True,blank=True,related_name='updatedadusers')
    updated_date = models.DateTimeField(default=timezone.now,null=True,blank=True)

med/models.py
from django.db.models.base import Model
from django.db.models.deletion import DO_NOTHING
from django.utils import timezone
from django.db import models
from accounts.models import User

# Create your models here.
class Department(models.Model):
    name = models.CharField(max_length=25)

    def __str__(self):
        return self.name

class Doctor(models.Model):
    name = models.CharField(max_length=25)
    department = models.ForeignKey(Department,on_delete=models.DO_NOTHING)

    def __str__(self):
        return self.name

class Area(models.Model):
    name = models.CharField(max_length=25)

    def __str__(self):
        return self.name

class Room(models.Model):
    roomno = models.CharField(max_length=10)
    area = models.ForeignKey(Area,on_delete=models.DO_NOTHING)

    def __str__(self):
        return self.roomno

class Bed(models.Model):
    bedno = models.CharField(max_length=10)
    room = models.ForeignKey(Room, on_delete=models.DO_NOTHING)

    def __str__(self):
        return self.bedno

class Patient(models.Model):
    MALE='Male'
    FEMALE='Female'
    OTHER = 'Other'
    GENDER = (
        (MALE,MALE),
        (FEMALE,FEMALE),
        (OTHER,OTHER),
    )
    fullname = models.CharField(max_length=120)
    mrno = models.CharField(max_length=15)
    gender = models.CharField(max_length=10,choices=GENDER)
    age = models.IntegerField()
    created_by = models.ForeignKey(User, on_delete=models.DO_NOTHING,null=True,blank=True,related_name='ptcreatedusers')
    created_date = models.DateTimeField(default=timezone.now)
    updated_by = models.ForeignKey(User, on_delete=models.DO_NOTHING,null=True,blank=True,related_name='ptupdatedusers')
    updated_date = models.DateTimeField(null=True,blank=True)

    def __str__(self):
        return self.fullname

class Visit(models.Model):
    patient = models.ForeignKey(Patient, on_delete=models.CASCADE)
    ipno = models.CharField(max_length=10,unique=True)
    department = models.ForeignKey(Department, on_delete=models.CASCADE)
    doctor = models.ForeignKey(Doctor, on_delete=models.CASCADE)
    building_floor = models.ForeignKey(Area, on_delete=models.DO_NOTHING)
    room = models.ForeignKey(Room, on_delete=models.DO_NOTHING)
    bedno = models.ForeignKey(Bed, on_delete=models.DO_NOTHING)

    def __str__(self):
        return self.patient.fullname

class KitchenUnit(models.Model):
    YES_NO = (
        (True,'Yes'),
        (False,'No'),
    )
    unit = models.CharField(max_length=50)
    active = models.BooleanField(choices=YES_NO)
    description = models.CharField(max_length=300,blank=True, null=True)

    def __str__(self):
        return self.unit

class MeasurementUnit(models.Model):
    MEASUREMENT = (
        ('Milligram','Milligram'),
        ('Gram','Gram'),
        ('Kilogram','Kilogram'),
        ('Milliliter','Milliliter'),
        ('Liter','Liter'),
        ('Bowl-Small','Bowl-Small'),
        ('Bowl-Medium','Bowl-Medium'),
        ('Bowl-Large','Bowl-Large'),
    )
    measurement = models.CharField(max_length=20,choices=MEASUREMENT)
    code = models.CharField(max_length=3)

    def __str__(self):
        return self.measurement

class ItemCategory(models.Model):
    YES_NO = (
        (True,'Yes'),
        (False,'No'),
    )
    category = models.CharField(max_length=30,blank=False, null=False)
    description = models.CharField(max_length=300,blank=True, null=True)
    active = models.BooleanField(choices=YES_NO)

    def __str__(self):
        return self.category

class DietItem(models.Model):
    YES_NO = (
        (True,'Yes'),
        (False,'No'),
    )
    item_name = models.CharField(max_length=60)
    item_category = models.ForeignKey(ItemCategory, on_delete=models.DO_NOTHING)
    kitchen_unit = models.ForeignKey(KitchenUnit, on_delete=models.DO_NOTHING)
    measurement_unit = models.ForeignKey(MeasurementUnit, on_delete=DO_NOTHING)
    default_unit_value = models.IntegerField(default=1)
    rate = models.DecimalField(max_digits=5, decimal_places=2)
    active = models.BooleanField(choices=YES_NO)

    def __str__(self):
        return self.item_name + ' (' + str(self.measurement_unit) + ')'

class DietOrder(models.Model):
    DIET_SLOT = (
        ('Breakfast','Breakfast'),
        ('Lunch','Lunch'),
        ('Dinner','Dinner'),
        ('Special','Special'),
    )
    patient = models.ForeignKey(Visit,on_delete=models.DO_NOTHING)
    category = models.ForeignKey(ItemCategory,on_delete=DO_NOTHING)
    item = models.ForeignKey(DietItem, on_delete=DO_NOTHING)
    quantity = models.IntegerField(default=1)
    special_instruction = models.CharField(max_length=300,null=True,blank=True)
    slot = models.CharField(max_length=20, choices=DIET_SLOT)
    delivery_date = models.DateField()
    created_by = models.ForeignKey(User, on_delete=models.DO_NOTHING,null=True,blank=True,related_name='dtcreatedusers')
    created_date = models.DateTimeField(default=timezone.now)
    updated_by = models.ForeignKey(User, on_delete=models.DO_NOTHING,null=True,blank=True,related_name='dtupdatedusers')
    updated_date = models.DateTimeField(null=True,blank=True)

med/forms.py
from django import forms
from django.forms import fields

from .models import Department, DietOrder, Doctor, Patient,Visit,Room,Bed,Area,ItemCategory

class PatientCreateForm(forms.ModelForm):
    MALE='Male'
    FEMALE='Female'
    OTHER = 'Other'
    GENDER = (
        (MALE,MALE),
        (FEMALE,FEMALE),
        (OTHER,OTHER),
    )
    fullname = forms.CharField(max_length=120, required=True)
    mrno = forms.CharField(max_length=15, required=True)
    gender = forms.ChoiceField(choices=GENDER,required=True)
    age = forms.IntegerField(required=True)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['room'].queryset = Room.objects.all()
        self.fields['bedno'].queryset = Bed.objects.all()

    class Meta:
        model = Visit
        exclude = ()
        fields = ('fullname','mrno','gender','age','ipno','building_floor','room','bedno','department')

class DietOrderForm(forms.ModelForm):
    MALE='Male'
    FEMALE='Female'
    OTHER = 'Other'
    GENDER = (
        (MALE,MALE),
        (FEMALE,FEMALE),
        (OTHER,OTHER),
    )
    DIET_SLOT = (
        ('-1','SELECT A SLOT'),
        ('Breakfast','Breakfast'),
        ('Lunch','Lunch'),
        ('Dinner','Dinner'),
        ('Special','Special'),
    )
    fullname = forms.CharField(max_length=120, required=True)
    mrno = forms.CharField(max_length=15, required=True)
    gender = forms.ChoiceField(choices=GENDER,required=True)
    age = forms.IntegerField(required=True)
    ipno = forms.CharField(max_length=10)
    department = forms.ModelChoiceField(queryset=Department.objects.all(),required=False)
    doctor = forms.ModelChoiceField(queryset=Doctor.objects.all())
    building_floor = forms.ModelChoiceField(queryset=Area.objects.all())
    room = forms.ModelChoiceField(queryset=Room.objects.all())
    bedno = forms.ModelChoiceField(queryset=Bed.objects.all())
    slot = forms.ChoiceField(choices=DIET_SLOT,required=True,widget=forms.Select(attrs={'onchange':'isSlotAvailable()'}))
    category = forms.ModelChoiceField(queryset=ItemCategory.objects.filter(active=True))
    special_instruction = forms.CharField(required=False, widget=forms.Textarea(attrs={'rows': 3, 'cols': 40}))
    quantity = forms.IntegerField(required=True)
    delivery_date = forms.DateField()
    patient = forms.CharField(widget = forms.HiddenInput(), required = False)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['room'].queryset = Room.objects.all()
        self.fields['bedno'].queryset = Bed.objects.all()
        self.fields['quantity'].initial = 1

    class Meta:
        model = DietOrder
        exclude = ('created_date',)
        fields = ('fullname','mrno','gender','age','ipno','department',
                    'room','bedno','category','item','building_floor',
                    'special_instruction','slot','quantity','delivery_date')

class DietOrderUpdateForm(forms.ModelForm):
    MALE='Male'
    FEMALE='Female'
    OTHER = 'Other'
    GENDER = (
        (MALE,MALE),
        (FEMALE,FEMALE),
        (OTHER,OTHER),
    )
    DIET_SLOT = (
        ('-1','SELECT A SLOT'),
        ('Breakfast','Breakfast'),
        ('Lunch','Lunch'),
        ('Dinner','Dinner'),
        ('Special','Special'),
    )
    fullname = forms.CharField(max_length=120,disabled=True)
    mrno = forms.CharField(max_length=15,disabled=True)
    gender = forms.ChoiceField(choices=GENDER,disabled=True)
    age = forms.IntegerField(disabled=True)
    ipno = forms.CharField(disabled=True)
    department = forms.ModelChoiceField(queryset=Department.objects.all(),disabled=True)
    doctor = forms.ModelChoiceField(queryset=Doctor.objects.all(),disabled=True)
    building_floor = forms.ModelChoiceField(queryset=Area.objects.all(),disabled=True)
    room = forms.ModelChoiceField(queryset=Room.objects.all(),disabled=True)
    bedno = forms.ModelChoiceField(queryset=Bed.objects.all(),disabled=True)
    slot = forms.ChoiceField(choices=DIET_SLOT)
    category = forms.ModelChoiceField(queryset=ItemCategory.objects.filter(active=True))
    special_instruction = forms.CharField(required=False, widget=forms.Textarea(attrs={'rows': 3, 'cols': 40}))
    quantity = forms.IntegerField(required=True)
    patient = forms.CharField(widget = forms.HiddenInput(),disabled=True)
    doid = forms.IntegerField(widget = forms.HiddenInput(),disabled=True)
    delivery_date = forms.DateField()

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['room'].queryset = Room.objects.all()
        self.fields['bedno'].queryset = Bed.objects.all()
        self.fields['quantity'].initial = 1

    class Meta:
        model = DietOrder
        exclude = ('created_date',)
        fields = ('fullname','mrno','gender','age','ipno','department',
                    'room','bedno','category','item','building_floor',
                    'special_instruction','slot','quantity','delivery_date')

diet/views.py
from django.shortcuts import render

# Create your views here.

med/templates/med/bed_dropdown_list_options.html
<option value="">---------</option>
{% for bed in beds %}
<option value="{{ bed.pk }}">{{ bed.bedno }}</option>
{% endfor %}

med/templates/med/diet_order.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block structure %}
{% include 'inc/structure.html'%}
{% endblock %}
{% block content %}
{% load med_custom_tags %}
<style>
    body{
        font-family: Arail, sans-serif;
    }
    .dmenu {
        text-align: center;
        font-family: 'Roboto Slab', serif;
        margin-top: 10%;
    }

    .dmenu a {
        color: white;
        background-color: #5A827F;
        padding: 5px 11px;
        border-style: 2px solid
    }

    .dmenu a:hover {

        border:1px solid #fff;
    }
    /* Formatting search box */
    .search-box{
        width: 300px;
        position: relative;
        display: inline-block;
        font-size: 14px;
    }
    .search-box input[type="text"]{
        height: 32px;
        padding: 5px 10px;
        border: 1px solid #CCCCCC;
        font-size: 14px;
    }
    .result{
        position: absolute;        
        z-index: 999;
        top: 100%;
        left: 0;
    }
    .search-box input[type="text"], .result{
        width: 100%;
        box-sizing: border-box;
    }
    /* Formatting result items */
    .result p{
        margin: 0;
        padding: 7px 10px;
        border: 1px solid #CCCCCC;
        border-top: none;
        cursor: pointer;
    }
    .result p:hover{
        background: #f2f2f2;
    }
</style>
<form method="post" name="dietorderform" action="" id="dietorderform" autocomplete="off" 
    data-rooms-url="{% url 'med:ajax_load_rooms' %}" data-beds-url="{% url 'med:ajax_load_beds' %}" 
    data-livesearch-url="{% url 'med:ajax_livesearch' %}">
{% csrf_token %}
<div class="panel panel-default">
    <div class="panel-heading">
        <h2 class="panel-title"><strong>Diet Form</strong></h2>
        <hr/>
    </div>
    <div class="panel-body ">
        <div class="row">
            <div class="col-md-12">
                <div class="row"><h5><span class="text-success">Diet Details</span></h5><hr/></div>
                <div class="form-group">
                    <div class="row">
                        <label class="col-md-1 control-label">Diet Category</label>
                        <div class="col-md-4">
                            {{ form.category|add_classes:'form-control' }}
                        </div>
                        <label class="col-md-1 control-label">Diet Item</label>
                        <div class="col-md-3">
                            {{ form.item|add_classes:'form-control' }}
                        </div>
                        <label class="col-md-1 control-label">Quantity</label>
                        <div class="col-md-2">
                            {{ form.quantity|add_classes:'form-control' }}
                        </div>
                    </div>
                    <div class="row">
                        <label class="col-md-1 control-label">Instructions</label>
                        <div class="col-md-3">
                            {{ form.special_instruction|add_classes:'form-control' }}
                        </div>
                        <label class="col-md-1 control-label">Delivery date</label>
                        <div class="col-md-3">
                            {{ form.delivery_date|add_classes:'form-control' }}
                        </div>
                        <label class="col-md-1 control-label">Time Slot</label>
                        <div class="col-md-3">
                            {{ form.slot|add_classes:'form-control' }}
                        </div>
                    </div>
                </div>
            </div>
        </div>  
        <div class="row align-items-start">
            <div class="col-md-12 ">
                <div class="row"><h5><span class="text-primary">Patient Info</span></h5><hr/></div>
                <div class="form-group">
                    <div class="row">
                        <label class="col-md-1 control-label">IP No</label>
                        <div class="col-md-5">
                            {{ form.ipno|add_classes:'form-control form-control-sm' }}
                            <div id="search-results"></div>
                        </div>
                        <div class="col-md-6"></div>
                    </div>
                </div>
                <div class="form-group">
                    <div class="row">
                        <label class="col-md-1 control-label">MR No</label>
                        <div class="col-md-4">
                            {{ form.mrno|add_classes:'form-control form-control-sm' }}
                        </div>
                        <label class="col-md-1 control-label">Patient Name</label>
                        <div class="col-md-6">
                            {{ form.fullname|add_classes:'form-control form-control-sm' }}
                        </div>
                    </div>
                </div>
                <div class="form-group">
                    <div class="row">
                        <label class="col-md-1">Age</label>
                        <div class="col-md-2">
                            {{ form.age|add_classes:'form-control form-control-sm' }}
                        </div>
                        <label class="col-md-1">Gender</label>
                        <div class="col-md-2">
                            {{ form.gender|add_classes:'form-control form-control-sm' }}
                        </div>
                        <label class="col-md-1 control-label">Doctor</label>
                        <div class="col-md-5">
                            {{ form.doctor|add_classes:'form-control form-control-sm' }}
                        </div>
                    </div>
                </div>
                <div class="form-group">
                    <div class="row">
                        <label class="col-md-1 control-label">Building/Floor</label>
                        <div class="col-md-3">
                            {{ form.building_floor|add_classes:'form-control form-control-sm' }}
                        </div>
                        <label class="col-md-1">Room</label>
                        <div class="col-md-3">
                            {{ form.room|add_classes:'form-control form-control-sm' }}
                        </div>
                        <label class="col-md-1">Bed</label>
                        <div class="col-md-3">
                            {{ form.bedno|add_classes:'form-control form-control-sm' }}
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="row"><div class="col-md-12"><hr/>{{ form.doid }}</div></div>       
        <div class="row">
            <div class="col-md-12">
                <div class="form-group">
                    <div class="row">
                        <div class="col-sm-3">
                        </div>
                        <div class="col-sm-6">
                            <button class="btn btn-md btn-danger" id="btnCancel">
                                Cancel <span class="glyphicon glyphicon-remove"></span>
                            </button>
                            <button class="btn btn-md btn-warning" id="btnReset">
                                Reset Form <span class="glyphicon glyphicon-refresh"></span>
                            </button>
                            <button class="btn btn-md btn-primary" id="btnSave" type="submit">
                                Save Data <span class="glyphicon glyphicon-cloud-upload"></span>
                            </button>
                        </div>
                        <div class="col-sm-3"></div>
                    </div>
                </div>
            </div>
        </div>
    </div>
  </div>
</form>

{% endblock %}

{% block footer%}

{% include 'inc/footer.html' %}
<script>
    marginbefore= document.getElementById('id_margin_before');
    marginafter = document.getElementById('id_margin_after');
    $(function () {
        marginafter.disabled = true;
        marginbefore.disabled = true;
    });
    $('#id_shift_margin').change(function(e){
        if ( $('#id_shift_margin').val()=='True' ){
            marginafter.disabled = false;
            marginbefore.disabled = false;
        }else{
            marginafter.disabled = true;
            marginbefore.disabled = true;
        }
    }); 
</script>
<script>
    $("#id_building_floor").change(function () {
      var url = $("#dietorderform").attr("data-rooms-url");  // get the url of the `load_cities` view
      var areaId = $(this).val();  // get the selected country ID from the HTML input
      $.ajax({                       // initialize an AJAX request
        url: url,                    // set the url of the request (= localhost:8000/hr/ajax/load-cities/)
        data: {
          'area': areaId       // add the country id to the GET parameters
        },
        success: function (data) {   // `data` is the return of the `load_cities` view function
          $("#id_room").html(data);  // replace the contents of the city input with the data that came from the server
        }
      });

    });

    $("#id_room").change(function () {
      var url = $("#dietorderform").attr("data-beds-url");  // get the url of the `load_cities` view
      var roomId = $(this).val();  // get the selected country ID from the HTML input
      $.ajax({                       // initialize an AJAX request
        url: url,                    // set the url of the request (= localhost:8000/hr/ajax/load-cities/)
        data: {
          'room': roomId       // add the country id to the GET parameters
        },
        success: function (data) {   // `data` is the return of the `load_cities` view function
          $("#id_bedno").html(data);  // replace the contents of the city input with the data that came from the server
        }
      });

    });
  </script>
   <script>
    $(function() {
       //$( "#id_delivery_date" ).datepicker();
       //$('#id_delivery_date').datepicker('setDate', 'today');
       $('#id_delivery_date').datepicker({ dateFormat: 'yy-mm-dd', minDate: 0});
        $('#id_delivery_date').datepicker('setDate', new Date());
    });
    $(document).ready(function(){
       $("#id_ipno").keyup(function(){
          enablePData();
          var url = $("#dietorderform").attr("data-livesearch-url");
          var query = $(this).val();
          if (query != "") {
            $.ajax({
              url: url,
              method: 'GET',
              data: {'q':query},
              success: function(data){
                $('#search-results').html(data);
                $('#search-results').css('display', 'block');
                $("#id_ipno").focusout(function(){
                    window.setTimeout(function() { $('#search-results').hide() }, 100);
                    //$('#search-results').css('display', 'none');
                });
                $("#id_ipno").focusin(function(){
                    $('#search-results').css('display', 'block');
                });
              }
            });
          } else {
          $('#search-results').css('display', 'none');
        }
      });
    });
    $("#search-results").mousedown(function(){
        
    });
    function fillPatientDetails(pk){
        ipno_elm = "#ipno_" + pk;
        ipno = $(ipno_elm).val();
        $('#id_ipno').val(ipno);
        mrno_elm = "#mrno_" + pk;
        mrno = $(mrno_elm).val();
        $('#id_mrno').val(mrno);
        fullname_elm = "#fullname_" + pk;
        fullname = $(fullname_elm).val();
        $('#id_fullname').val(fullname);
        age_elm = "#age_" + pk;
        age = $(age_elm).val();
        $('#id_age').val(age);
        gender_elm = "#gender_" + pk;
        gender = $(gender_elm).val();
        $('#id_gender').val(gender);
        doctor_elm = "#doctor_" + pk;
        doctor = $(doctor_elm).val();
        $('#id_doctor').val(doctor);
        building_floor_elm = "#building_floor_" + pk;
        building_floor = $(building_floor_elm).val();
        $('#id_building_floor').val(building_floor);
        room_elm = "#room_" + pk;
        room = $(room_elm).val();
        $('#id_room').val(room);
        bedno_elm = "#bedno_" + pk;
        bedno = $(bedno_elm).val();
        $('#id_bedno').val(bedno);
        disablePData();
    }
    function disablePData(){
        $("#id_gender").attr("disabled", "disabled");
        $("#id_mrno").attr("disabled", "disabled");
        $("#id_fullname").attr("disabled", "disabled");
        $("#id_age").attr("disabled", "disabled");
        $("#id_doctor").attr("disabled", "disabled");
        $("#id_building_floor").attr("disabled", "disabled");
        $("#id_room").attr("disabled", "disabled");
        $("#id_bedno").attr("disabled", "disabled");
    }
    function enablePData(){
        $("#id_gender").removeAttr("disabled");
        $("#id_mrno").removeAttr("disabled");
        $("#id_fullname").removeAttr("disabled");
        $("#id_age").removeAttr("disabled");
        $("#id_doctor").removeAttr("disabled");
        $("#id_building_floor").removeAttr("disabled");
        $("#id_room").removeAttr("disabled");
        $("#id_bedno").removeAttr("disabled");
    }
 </script>
{% endblock %}

med/templates/med/diet_order_form.html
{% extends 'base.html' %}
{% block structure %}
{% include 'inc/structure.html'%}
{% endblock %}
{% block content %}
{% load med_custom_tags %}

{% endblock %}
{% block footer%}
{% include 'inc/footer.html' %}
{% endblock %}