Swasthya/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
	path('', include('accounts.urls')),
    path('console/', include('console.urls')),
    path('employee/', include('Employee.urls')),
    path('leave/', include('leave.urls')),
    path('eattendance/', include('eattendance.urls')),
    path('med/', include('med.urls')),
    path('admin/', admin.site.urls),
]

accounts/urls.py
from django.urls import path
from . import views
from accounts.views import SignUpView


app_name = 'accounts'

urlpatterns = [
    #path('login/',views.login_view,name='login'),
    path('logout/',views.logout_view,name='logout'),
    path('signup/',SignUpView.as_view(), name='signup'),
     path('login/', views.LoginView.as_view(), name='login'),
    path('profile/', views.ProfileView.as_view(), name='profile'),
    path('user/change-password/',views.changepassword,name='changepassword'),
    path('user/profile/view/',views.user_profile_view,name='userprofile'),
    path('',views.home,name='home'),

    #Users Views
    path('users/all',views.users_list,name='users'),
    path('users/<int:id>/block',views.users_block,name='userblock'),
    path('users/<int:id>/unblock',views.users_unblock,name='userunblock'),
    path('users/blocked/all',views.users_blocked_list,name='erasedusers'),
]

med/urls.py
from django.urls import path
from . import views

app_name = 'med'

urlpatterns = [
    path('visit/create',views.VisitCreateView.as_view(),name='create-visit'),
    path('visit/<int:id>/', views.VisitDetailView.as_view(), name='visit-detail'),

    path('diet/create',views.DietOrderView.as_view(),name='create-diet'),
    path('<int:id>/edit',views.DietOrderUpdateView.as_view(),name='leave-update'),
    path('diet/<int:id>/',views.DietOrderDetailView.as_view(),name='dietorder-detail'),
    path('diet/list/', views.DietOrderList.as_view(), name='list-diet'),

    path('ajax/load_rooms', views.load_rooms, name='ajax_load_rooms'), 
    path('ajax/load_beds', views.load_beds, name='ajax_load_beds'), 
    path('ajax/load_livesearch_ipno', views.livesearch_ipno, name='ajax_livesearch'), 
]

templates/commons/login.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% load static %}
{% block menu_dropdown %}
{% include 'inc/nav_dropdown_menu.html'%}
{% endblock %}
{% block content %}
{% load custom_tags %}
  {% if form.errors %}
    <p>Your username and password didn't match. Please try again.</p>
  {% endif %}

  {% if next %}
    {% if user.is_authenticated %}
      <p>Your account doesn't have access to this page. To proceed,
      please login with an account that has access.</p>
    {% else %}
      <p>Please login to see this page.</p>
    {% endif %}
  {% endif %}
  <div class="container">
    <div class="row">
      <div class="col-sm-9 col-md-7 col-lg-5 mx-auto">
        <div class="card card-signin my-5">
          <div class="bg-image hover-overlay ripple" data-mdb-ripple-color="light" align=center>
            <img width="192" height="208" 
              src="{% static 'assets/images/big-l.png' %}"
              class="img-fluid"/> 
              <h5 class="card-title" style="color: rgb(18, 114, 22); font-size: 36px;">Swasthya</h5>
              <span style="color: rgb(173, 35, 0);"">Healthcare Solutions</span>
            <a href="#!">
              <div class="mask" style="background-color: rgba(251, 251, 251, 0.15)"></div>
            </a>
          </div>
          <div class="card-body">
            <h5 class="card-title text-left">Sign In</h5>
            <form class="form-signin" method="POST">
              {% csrf_token %}
              <div class="form-label-group">
                {{ form.username|add_classes:'form-control' }}
                <label for="inputEmail">{{ form.username.label_tag }}</label>
              </div>

              <div class="form-label-group">
                {{ form.password|add_classes:'form-control' }}
                <label for="inputPassword">{{ form.password.label_tag }}</label>
              </div>

              <button class="btn btn-lg btn-primary btn-block text-uppercase" type="submit">Sign in</button>
              <!--<hr class="my-4">
              <p><a href="{% url 'accounts:changepassword' %}">Lost password?</a></p>
              <button class="btn btn-lg btn-google btn-block text-uppercase" type="submit"><i class="fab fa-google mr-2"></i> Sign in with Google</button>
              <button class="btn btn-lg btn-facebook btn-block text-uppercase" type="submit"><i class="fab fa-facebook-f mr-2"></i> Sign in with Facebook</button>
              -->
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
  {# Assumes you setup the password_reset view in your URLconf #}
  

{% endblock %}
{% block footer%}
{% include 'inc/footer.html' %}
{% endblock %}

templates/commons/signup.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %}Sign Page{% endblock title %}

{% block content %} 
    <h2>Sign Up
        
    </h2>
    <form method="post">
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit">Register</button>
        <br><br>
        <a href="">Home</a>
    </form>
{% endblock content %}

templates/commons/user_profile.html
<!-- base.html -->
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Swasthya</title>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.7.5/css/bulma.css">
  <script defer src="https://use.fontawesome.com/releases/v5.3.1/js/all.js"></script>
</head>
<body>
  <nav class="navbar" role="navigation" aria-label="main navigation">
    <div class="navbar-brand">
      <a class="navbar-item" href="/">
        Swasthya
      </a>
  
      <a role="button" class="navbar-burger burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
        <span aria-hidden="true"></span>
        <span aria-hidden="true"></span>
        <span aria-hidden="true"></span>
      </a>
    </div>

    <div id="navbar-menu" class="navbar-menu">
      {% if request.user.is_authenticated %}
      <div class="navbar-start">
        <a class="navbar-item" href="{% url 'accounts:profile' %}">
          Profile
        </a>
        <!-- update this later -->
        <a class="navbar-item" href="#">
          Create Survey
        </a>
      </div>
      {% endif %}

      <div class="navbar-end">
        <div class="navbar-item">
          {% if request.user.is_authenticated %}
          <a class="button is-info" href="{% url 'accounts:logout' %}">Logout</a>
          {% else %}
          <div class="buttons">
            <a class="button is-primary" href="{% url 'accounts:signup' %}">
              <strong>Sign up</strong>
            </a>
            <a class="button is-light" href="{% url 'accounts:login' %}">
              Log in
            </a>
          </div>
          {% endif %}
        </div>
      </div>
    </div>
  </nav>

  {% block content %}

  {% endblock %}
</body>
</html>